language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: peter@superlativecode.com
  api_key:
    secure: XrezOs0WS0P3tqftMtH0Z48U55D+33D8tAAa6fucY/rrIrr2lq3SdgJ/dZxV5YEIgoyHFEcf9u/a4aMBNh0c18xVRP2NzqIyRjEPks+Kcvq552RVBQpZGkhAcM/z4CKqxxRy6qlmVVHZQNDc/iT0TfnU14+DYkLUzAX452pF5hFMYgSJo5x2SlBbiKXBkJ6pLF7va8Zde2IOghiSkjLFjTi9X1zNZvnQcDm5CvQb0E9x06yaj/vPUZGNcHFIpYYobLEk4P2vytg0g1ILmLQjowHyjIOoP1KcNBc7raWqmjOnN1TvIsSMyUvgMooNt1tlE5kevIGxVMSUSIzLfLB7KRDo4OJum0aIAa691VX26nA4EUI1r6Zq1pkQVVl3j96e5VM5vlf6dTZdF3+yDcOH97Of2JBz+tjsHeaT4sn+smC/5HtFwPVc9ie3ZOFyKyAlO1Frur1sZLo9Iq5gKx8a/4qE9MnzQSsvUgcvazvtKRTT8s31yXZwYH3y82hxQyKXcxtg4uwY4ezmDsRlH75FrJt9822S/DB8LifypDRRAYbVyCZP7Cy89eQ+XOmO9rHjAk0fNsgDEfxDoBl1wG2dMxZ2sPSXvoCFPpqcD1jDgLS/y7GdT20TQHG1JOw2ZRkO5VY1UJdn3Ella7hguZpSqOfxv+LndVAl50Jx8f3eBho=
  on:
    tags: true
    repo: peterdemartini/changing-interval
